version: "3"
services:
    mysql:
        build: ./mysql
        container_name: mysql_database
        volumes:
            - ./mysql/db:/docker-entrypoint-initdb.d
        environment:
            MYSQL_ROOT_PASSWORD: my-secret-pw
        networks:
            - test
        ports:
            - "3306:3306"

    go_app:
        build: ./go
        container_name: go_app
        networks:
            - test
        ports:
            - "8080:80"

networks:
    test:
        external: true
