version: "3"
services:
    mysql:
        build: ./mysql
        container_name: mysql
        volumes:
            - ./mysql/db:/docker-entrypoint-initdb.d
        environment:
            MYSQL_ROOT_PASSWORD: my-secret-pw
            MYSQL_DATABASE: sample
            MYSQL_USER: gopher
            MYSQL_PASSWORD: setsetset
        networks:
            - production_network
        ports:
            - "33060:3306"

    go_app:
        build: ./go
        container_name: go_app
        networks:
            - production_network
        ports:
            - "8080:80"
        depends_on:
            - mysql
        environment:
            WAIT_HOSTS: mysql

networks:
    production_network:
        external: true
